spring.application.name=order-service
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.jpa.show-sql=true